<?xml version="1.0" encoding="UTF-8"?> 
<?xml-stylesheet type="text/css" href="style12.css"?> 
<!DOCTYPE container [
<!ELEMENT container (product, name, value, price)>
<!ELEMENT product (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ENTITY symbol ":">
]>
<container>
<product>Products</product> 
<price>Price</price> 
<name>Orange&symbol;</name> 
<value>0.8$</value> 
<name>Milk&symbol;</name> 
<value>1.8$</value> 
<name>biscuit&symbol;</name> 
<value>2$</value> 
<name>beef&symbol;</name> 
<value>15$</value> 
<name>cake&symbol;</name> 
<value>20$</value> 
</container> 